package com.codemitra.backend.repository;

import com.codemitra.backend.model.ScrapedProblemEntity;
import java.util.List;
import java.util.Optional;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * Repository for staging queue records generated by source scrapers.
 */
public interface ScrapedProblemRepository extends JpaRepository<ScrapedProblemEntity, Long> {

    Optional<ScrapedProblemEntity> findBySourceIdAndExternalId(Long sourceId, String externalId);

    boolean existsByContentHashAndImportStatusIn(String contentHash, List<String> statuses);

    List<ScrapedProblemEntity> findByImportStatusOrderByScrapedAtDescIdDesc(String importStatus);

    long countByImportStatus(String importStatus);

    long countBySourceIdAndImportStatus(Long sourceId, String importStatus);
}
